import type { Metadata } from "next";
import "./globals.scss";
import { Header } from "@/widgets/header/ui/header";
import localFont from "next/font/local";

const font = localFont({
  src: [
    {
      path: "./../../public/font/CeraPro-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    {
      path: "./../../public/font/CeraPro-Bold.woff2",
      weight: "700",
      style: "normal",
    },
    {
      path: "./../../public/font/CeraPro-Black.woff2",
      weight: "900",
      style: "normal",
    },
    {
      path: "./../../public/font/CeraPro-Medium.woff2",
      weight: "600",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={font.className}>
        <Header />
        <main>{children}</main>
      </body>
    </html>
  );
}
